---
- name: Set up Ubuntu based OS for development
  hosts: all
  become: yes
  tasks:
  - name: Install package dependencies
    apt:
      name: docker.io,python3-pip,sshpass,git
      state: present

  - name: Install docker-compose
    pip:
      name: docker-compose>=1.29
      state: present
