---
name: 'OPI Storage PoC CI'

on:
  push:
    branches: [ main ]
    paths:
      - 'storage/**'
      - '.github/workflows/poc-storage.yml'
      - '.github/workflows/poc-storage-poc.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'storage/**'
      - '.github/workflows/poc-storage.yml'
      - '.github/workflows/poc-storage-poc.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: makefile-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  storage-shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: storage shellcheck
      run: |
        make -C storage shellcheck

  run_storage_poc:
    needs: storage-shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run Storage PoC
      run: docker-compose -f "docker-compose.yml" up --detach --build
      working-directory: storage
